### ISSUE TITLE
Release 1.5.0 changed behaviour of MIME.extensions with nil

### ISSUE THREAD

**Issue by chess4ever** [elixir-plug/mime#43]
In `1.4.0`:
```elixir
iex> MIME.extensions(nil)                      
[]
```

In `1.5.0`:
```elixir
iex> MIME.extensions(nil) 
** (FunctionClauseError) no function clause matching in MIME.downcase/2    
    
    The following arguments were given to MIME.downcase/2:
    
        # 1
        nil
    
        # 2
        ""
    
    Attempted function clauses (showing 3 out of 3):
    
        defp downcase(<<h, t::binary()>>, acc) when is_integer(h) and (h >= 65 and h <= 90)
        defp downcase(<<h, t::binary()>>, acc)
        defp downcase(<<>>, acc)
    
    (mime 1.5.0) lib/mime.ex:2: MIME.downcase/2
    (mime 1.5.0) lib/mime.ex:2: MIME.extensions/1
```

**Comment by josevalim** [comment]
The fact it worked on `nil` was an accident. The specs for the function documented a string type was expected: https://hexdocs.pm/mime/MIME.html#extensions/1 - so please update your code accordingly.

Thank you!
